version: '3'

services:
  gz_sim:
    image: her_vrx_harmonic:latest  # ←あなたが作ったイメージ
    runtime: nvidia
    environment: 
      - PYTHONUNBUFFERED=1
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XDG_RUNTIME_DIR
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - XAUTHORITY=$XAUTHORITY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/user:/run/user:ro
      - ../:/home/koki-22/Her_VRX_docker
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]